version: '3.7'

networks:
  drone-net:
    external: false

services:
  drone-server:
    image: drone/drone:2
    env_file:
      - ./envs/drone-server.env
    volumes:
      - /var/lib/drone:/data
    networks:
      - drone-net
    ports:
      - 8080:80
      - 8443:443
    restart: always

  drone-runner:
    image: drone/drone-runner-docker:1
    env_file:
      - ./envs/drone-runner.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - drone-net
    ports:
      - 3000:3000
    restart: always

